---
# handlers file for server
- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: restart php
  service:
    name: php-fpm
    state: restarted
    enabled: yes

- name: restart php8
  service:
    name: php8.1-fpm
    state: restarted
    enabled: yes

- name: restart mysql
  service:
    name: mysql
    state: restarted