--- 
- name: Install nginx Repo.
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ nginx_repo_yum }}"

- name: Enabling repository nginx
  shell: yum-config-manager --enable nginx-mainline

- name: Installing yum-utils/epel-release
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - yum-utils

- name: Installing dependency wordpress
  yum: name={{ item }} state=latest
  with_items:
    - nginx
    - vim
    - mariadb-server
    - mariadb
    - MySQL-python 

- name: Start MySQL and enable on boot
  service:
    name: mariadb
    state: restarted
    enabled: yes

- name: Template archive default.conf
  template:
     src: wordpress.conf.j2
     dest: /etc/nginx/conf.d/default.conf

- name: Start nginx and enable on boot
  service:
    name: nginx
    state: restarted
    enabled: yes

# tasks file for php
- name: Download repository remi-release-7
  get_url:
      url: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
      dest: /tmp/remi-release-7.rpm
      mode: 0777

- name: Add repository remi-release-7
  yum: name=/tmp/remi-release-7.rpm state=present

- name: Enabling remi-php73
  shell: yum-config-manager --enable remi-php73

- name: Installing php73
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-fpm
    - php-common 
    - php-opcache 
    - php-mcrypt 
    - php-cli 
    - php-gd 
    - php-curl 
    - php-mysqlnd

- name: Start php and enable on boot
  service:
    name: php-fpm
    state: started
    enabled: yes