---
- include_tasks: RedHat.yml
  when: ansible_distribution_major_version == '8'

- include_tasks: CentOS-7.yml
  when: ansible_distribution_major_version == '7'

- name: Install Mysql
  include_tasks: mysql.yml
- name: Install wordpress
  include_tasks: wordpress.yml
  