---
# tasks file for php
- name: Instalando yum-utils/epel-release
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - yum-utils

- name: Baixando repositório remi-release-7
  get_url:
      url: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
      dest: /tmp/remi-release-7.rpm
      mode: 0777

- name: Adicionando repositório remi-release-7
  yum: name=/tmp/remi-release-7.rpm state=present

- name: Habilitando remi-php73
  shell: yum-config-manager --enable remi-php73

- name: Instalando php73
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-fpm
    - php-common 
    - php-opcache 
    - php-mcrypt 
    - php-cli 
    - php-gd 
    - php-curl 
    - php-mysqlnd

- name : Substituindo user www.conf
  shell: sed -i 's/user = apache/user = nginx/g' /etc/php-fpm.d/www.conf
  
- name: Substituindo group www.conf
  shell: sed -i 's/group = apache/group = nginx/g' /etc/php-fpm.d/www.conf
  
